import { useRef,useState,useEffect } from 'react';
import { Play,RotateCcw,Headphones } from 'lucide-react';
import { api } from '../lib/api';
import type { Attempt,Section } from '../../../shared/api';
export function AudioPlayer({attempt,section,visible}:{attempt:Attempt;section:Section;visible:boolean}){
 const ref=useRef<HTMLAudioElement>(null);const [url,setUrl]=useState('');const [error,setError]=useState('');const [playing,setPlaying]=useState(false);const [ended,setEnded]=useState(false);const positionKey=`hub-audio:${attempt.user_id}:${attempt.id}:${section.id}`;const hasStarted=useRef(Boolean(attempt.playback[section.id]));
 const mock=attempt.mode==='mock'&&attempt.status==='active';
 useEffect(()=>()=>{ref.current?.pause();},[]);
 async function play(){try{setError('');const d=await api<{url:string}>(`/attempts/${attempt.id}/audio/${section.id}${hasStarted.current?'/recover':''}`,hasStarted.current?'GET':'POST');hasStarted.current=true;setUrl(d.url);}catch(e){setError(e instanceof Error?e.message:'Audio could not load.');}}
 useEffect(()=>{if(url&&ref.current){const audio=ref.current;audio.load();}},[url]);
 return <div className="audio-player" style={{display:visible?'block':'none'}}><div className="row between"><div className="row"><Headphones size={21}/><div><strong>{section.title}</strong><small>Synthesized demonstration audio · {mock?'One play, with recovery':'Replay allowed'}</small></div></div>{!url&&<button className="button primary small-button" onClick={play}><Play size={15}/>{hasStarted.current?'Resume saved audio':'Play audio'}</button>}</div>{url&&<><audio ref={ref} src={url} controls={!mock} aria-label={section.title} onLoadedMetadata={()=>{const a=ref.current!;const saved=Number(localStorage.getItem(positionKey)??0);if(saved>0&&saved<a.duration)a.currentTime=saved;void a.play().catch(()=>setError('Playback was blocked. Press Continue audio to start.'));}} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onTimeUpdate={()=>{if(ref.current)localStorage.setItem(positionKey,String(ref.current.currentTime));}} onEnded={()=>{setEnded(true);setPlaying(false);}} onError={()=>setError('The audio could not load. Check your connection and retry from the saved position.')}/>{mock&&<p className="text-sm">{ended?'Audio completed.':playing?'Audio is playing. Playback continues while you move between questions.':'Audio paused by the browser.'}</p>}{!playing&&!ended&&<button className="text-button" onClick={()=>void ref.current?.play().catch(()=>setError('Playback unavailable. Retry loading audio.'))}>Continue audio</button>}</>}{error&&<div className="notice error" role="alert">{error}<button className="text-button" onClick={play}><RotateCcw size={16}/>Retry audio</button></div>}</div>;
}
