import { useState } from 'react';
import { Link,NavLink,Outlet,useNavigate } from 'react-router-dom';
import { BookOpen,LayoutDashboard,LibraryBig,ChartNoAxesCombined,Bookmark,CalendarDays,Settings,LogOut,ArrowUpRight,Bell,Menu,X,GraduationCap,LifeBuoy } from 'lucide-react';
import { useSession } from '../lib/session';
import { api,clearDrafts,queryClient } from '../lib/api';
export function Brand(){const {config}=useSession();return <Link className="brand" to="/"><span className="brand-mark"><BookOpen size={23}/></span><span>{config?.brand??'IELTS Practice Hub'}<small>A LITTLE PRACTICE. A BIGGER FUTURE.</small></span></Link>;}
const nav=[['/dashboard','Overview',LayoutDashboard],['/library','Practice library',LibraryBig],['/progress','My progress',ChartNoAxesCombined],['/mistakes','Mistake notebook',Bookmark],['/study-plan','Study plan',CalendarDays]] as const;
export function Layout(){const {user,refresh}=useSession();const [open,setOpen]=useState(false);const navigate=useNavigate();
 async function logout(){await api('/auth/logout','POST');clearDrafts();queryClient.clear();await refresh();navigate('/');}
 return <div className={user?'app-shell':'public-shell'}><a className="skip-link" href="#main">Skip to content</a>{user?<><aside className={`sidebar ${open?'open':''}`}><Brand/><button className="mobile-close icon-button" aria-label="Close navigation" onClick={()=>setOpen(false)}><X/></button><p className="nav-label">YOUR LEARNING SPACE</p><nav aria-label="Main navigation">{nav.map(([to,label,Icon])=><NavLink key={to} to={to} onClick={()=>setOpen(false)}><Icon size={19}/>{label}</NavLink>)}</nav><div className="sidebar-note"><span className="tiny-star">✧</span><h4>Small steps. Steady progress.</h4><p>Your next practice session is a step toward your goal.</p><Link to="/library">Find your next test <ArrowUpRight size={15}/></Link></div><nav className="bottom-nav" aria-label="Account navigation">{user.role!=='student'&&<a href="/admin"><GraduationCap size={19}/>Staff workspace<ArrowUpRight size={14}/></a>}<NavLink to="/help"><LifeBuoy size={19}/>Help & resources</NavLink><NavLink to="/settings"><Settings size={19}/>Settings</NavLink></nav><div className="sidebar-user"><span className="avatar">{user.name.slice(0,1)}</span><div><strong>{user.name}</strong><small>{user.role==='student'?'Your learning journey':user.role}</small></div><button aria-label="Log out" className="icon-button" onClick={logout}><LogOut size={17}/></button></div></aside><div className="workspace"><header className="app-header"><button className="mobile-toggle icon-button" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu/></button><span className="header-breadcrumb">Your space to grow <span>/</span> IELTS preparation</span><div className="row"><Link className="header-goal" to="/settings">{user.profile?.test_type==='general'?'General Training':'Academic'}<span>•</span>Target {user.profile?.target_band?.toFixed(1)??'not set'}</Link><Link className="icon-button" to="/notifications" aria-label="Notifications"><Bell size={19}/></Link></div></header><main id="main" className="main"><Outlet/></main><footer className="app-footer">A little more confident, every day.<span>Independent practice platform · <Link to="/privacy">Privacy</Link></span></footer></div></>:<><header className="public-header"><Brand/><nav aria-label="Main navigation"><NavLink to="/library">Practice library</NavLink><NavLink to="/how-it-works">How it works</NavLink><NavLink to="/pricing">Plans</NavLink></nav><div className="row"><Link className="login-link" to="/login">Log in</Link><Link className="button primary small-button" to="/register">Start learning <ArrowUpRight size={16}/></Link></div></header><main id="main"><Outlet/></main><footer className="public-footer"><Brand/><p>Independent IELTS practice. No affiliation with the IELTS owners.</p><div>{['help','contact','privacy','terms'].map(p=><Link to={'/'+p} key={p}>{p[0].toUpperCase()+p.slice(1)}</Link>)}</div></footer></>}</div>;
}
