import { useState,useRef,useEffect } from 'react';
import { Mic,Square,Upload,Check,Download } from 'lucide-react';
import { csrfToken,key,api } from '../lib/api';
import { recordingDraft } from '../lib/recordingStore';
import type { Attempt,Question } from '../../../shared/api';
export function Recorder({attempt,q,onUploaded,flush}:{attempt:Attempt;q:Question;onUploaded:(a:Attempt)=>void;flush:()=>Promise<Attempt>}){
 const draftId=`${attempt.user_id}:${attempt.id}:${q.id}`;const [blob,setBlob]=useState<Blob>();const [url,setUrl]=useState('');const [recording,setRecording]=useState(false);const [error,setError]=useState('');const [progress,setProgress]=useState<number|null>(null);const [seconds,setSeconds]=useState(0);const [prep,setPrep]=useState<number|null>(null);const recorder=useRef<MediaRecorder|null>(null);const stream=useRef<MediaStream|null>(null);const uploadKey=useRef(key());const startAt=useRef(0);const saved=attempt.recordings.some(r=>r.question_id===q.id);
 useEffect(()=>{void recordingDraft(draftId).then(b=>b&&setBlob(b)).catch(()=>{});return()=>{recorder.current?.state==='recording'&&recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());};},[draftId]);
 useEffect(()=>{if(blob){const u=URL.createObjectURL(blob);setUrl(u);return()=>URL.revokeObjectURL(u);}},[blob]);
 useEffect(()=>{if(!recording)return;const timer=setInterval(()=>{const elapsed=Math.floor((performance.now()-startAt.current)/1000);setSeconds(elapsed);if(elapsed>=(q.response_seconds??120))recorder.current?.stop();},250);return()=>clearInterval(timer);},[recording,q.response_seconds]);
 useEffect(()=>{if(prep===null||prep===0)return;const end=performance.now()+prep*1000;const timer=setInterval(()=>setPrep(Math.max(0,Math.ceil((end-performance.now())/1000))),500);return()=>clearInterval(timer);},[prep===null]);
 async function start(){try{setError('');const s=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=s;const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(m=>MediaRecorder.isTypeSupported(m));const r=new MediaRecorder(s,mime?{mimeType:mime}:undefined);recorder.current=r;const chunks:Blob[]=[];r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};r.onstop=()=>{const b=new Blob(chunks,{type:r.mimeType});setBlob(b);uploadKey.current=key();void recordingDraft(draftId,b).catch(()=>setError('Could not store a local recording draft. Download your recording before leaving.'));setRecording(false);s.getTracks().forEach(t=>t.stop());};startAt.current=performance.now();setSeconds(0);setRecording(true);r.start(1000);}catch(e){setError('Microphone unavailable. Allow microphone permission or choose a supported audio file below.');}}
 async function upload(){if(!blob)return;try{await flush();setError('');setProgress(0);const form=new FormData();form.set('question_id',q.id);form.set('upload_key',uploadKey.current);form.set('recording',blob,`response.${blob.type.includes('mp4')?'m4a':blob.type.includes('wav')?'wav':blob.type.includes('ogg')?'ogg':'webm'}`);await new Promise<void>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST',`/api/v1/attempts/${attempt.id}/recordings`);xhr.setRequestHeader('Accept','application/json');xhr.setRequestHeader('X-XSRF-TOKEN',csrfToken());xhr.setRequestHeader('X-Requested-With','XMLHttpRequest');xhr.upload.onprogress=e=>e.lengthComputable&&setProgress(Math.round(e.loaded/e.total*100));xhr.onerror=()=>reject(new Error('Upload interrupted. Your recording is kept here for retry.'));xhr.onload=()=>{const d=JSON.parse(xhr.responseText);if(xhr.status>=400){reject(new Error(d.message??'Upload failed.'));return;}onUploaded(d.attempt);resolve();};xhr.send(form);});await recordingDraft(draftId,null);setProgress(null);setBlob(undefined);setUrl('');}catch(e){setError(e instanceof Error?e.message:'Upload failed.');setProgress(null);}}
 return <div className="recorder"><h3>{q.prompt}</h3><p className="muted text-sm">This is a recorded practice simulation, not an official live examiner interview.</p>{q.preparation_seconds? <div className="row"><button className="button secondary small-button" onClick={()=>setPrep(q.preparation_seconds??60)}>Start preparation timer</button><span role="timer">{prep===null?`${q.preparation_seconds}s preparation`:prep>0?`${prep}s remaining`:'Preparation complete'}</span></div>:null}<div className="recording-box"><span className={`recording-icon ${recording?'live':''}`}><Mic size={28}/></span><strong>{recording?`Recording · ${seconds}s / ${q.response_seconds}s`:saved?'A recording is uploaded':blob?'Your recording is ready':'Give your ideas a voice.'}</strong><p className="text-sm muted">Up to {Math.round((q.response_seconds??120)/60)} minutes for this response.</p>{recording?<button className="button secondary" onClick={()=>recorder.current?.stop()}><Square size={15}/>Stop recording</button>:<button className="button primary" disabled={progress!==null||attempt.status!=='active'} onClick={start}><Mic size={17}/>{saved||blob?'Record again':'Start recording'}</button>}</div>{url&&<><audio src={url} controls aria-label="Preview your response"/><div className="row wrap"><button className="button primary" disabled={progress!==null} onClick={upload}><Upload size={16}/>{progress!==null?`Uploading ${progress}%`:'Upload response'}</button><a href={url} download="my-speaking-response" className="text-button"><Download size={16}/>Keep a copy</a></div></>}{saved&&!blob&&<p className="correct-text"><Check size={16}/>Uploaded and saved privately.</p>}<label className="upload-alternative">Or choose an audio file<input type="file" accept="audio/*,.webm,.m4a" disabled={recording||progress!==null} onChange={e=>{const f=e.target.files?.[0];if(f){if(f.size>25*1024*1024){setError('Maximum file size is 25 MB.');return;}setBlob(f);uploadKey.current=key();void recordingDraft(draftId,f);}}}/><small>WebM, Ogg, MP4/M4A, MP3 or WAV · maximum 25 MB</small></label>{error&&<div className="notice error" role="alert">{error}</div>}</div>;
}
