<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::table('users', function(Blueprint $t) { $t->string('role')->default('student')->index(); $t->boolean('suspended')->default(false); $t->json('profile')->nullable(); $t->timestamp('deletion_requested_at')->nullable(); });
  Schema::create('collections', function(Blueprint $t){ $t->id(); $t->string('title'); $t->string('slug')->unique(); $t->text('description')->nullable(); $t->boolean('is_mock')->default(false); $t->json('sequence')->nullable(); $t->timestamps(); });
  Schema::create('exams', function(Blueprint $t){ $t->id(); $t->string('slug')->unique(); $t->string('title'); $t->text('description'); $t->string('skill')->index(); $t->string('test_type')->index(); $t->string('status')->default('draft')->index(); $t->boolean('premium')->default(false); $t->boolean('sample')->default(false); $t->boolean('demo')->default(true); $t->unsignedInteger('duration_seconds')->default(1200); $t->foreignId('collection_id')->nullable()->constrained('collections')->nullOnDelete(); $t->json('tags')->nullable(); $t->json('draft'); $t->unsignedInteger('published_version')->nullable(); $t->unsignedInteger('revision')->default(0); $t->timestamps(); });
  Schema::create('exam_versions', function(Blueprint $t){ $t->id(); $t->foreignId('exam_id')->constrained()->restrictOnDelete(); $t->unsignedInteger('number'); $t->json('content'); $t->json('scoring'); $t->foreignId('published_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('created_at'); $t->unique(['exam_id','number']); });
  Schema::create('attempts', function(Blueprint $t){ $t->uuid('id')->primary(); $t->foreignId('user_id')->constrained()->cascadeOnDelete(); $t->foreignId('exam_id')->constrained()->restrictOnDelete(); $t->foreignId('exam_version_id')->constrained()->restrictOnDelete(); $t->string('start_key'); $t->string('mode'); $t->string('status')->default('active')->index(); $t->json('section_ids'); $t->json('answers'); $t->json('flags'); $t->json('notes'); $t->json('highlights'); $t->json('playback'); $t->unsignedInteger('revision')->default(0); $t->timestamp('started_at'); $t->timestamp('deadline_at')->nullable()->index(); $t->timestamp('paused_at')->nullable(); $t->timestamp('submitted_at')->nullable(); $t->unsignedInteger('remaining_seconds')->nullable(); $t->json('result')->nullable(); $t->timestamps(); $t->unique(['user_id','start_key']); $t->index(['user_id','status']); });
  Schema::create('attempt_mutations', function(Blueprint $t){ $t->id(); $t->foreignUuid('attempt_id')->constrained()->cascadeOnDelete(); $t->uuid('request_key'); $t->unsignedInteger('revision'); $t->timestamps(); $t->unique(['attempt_id','request_key']); });
  Schema::create('recordings', function(Blueprint $t){ $t->uuid('id')->primary(); $t->foreignUuid('attempt_id')->constrained()->cascadeOnDelete(); $t->string('question_id'); $t->uuid('upload_key'); $t->string('disk'); $t->string('path'); $t->string('mime'); $t->unsignedBigInteger('size'); $t->timestamp('expires_at')->nullable(); $t->timestamps(); $t->unique(['attempt_id','upload_key']); });
  Schema::create('assessments', function(Blueprint $t){ $t->id(); $t->foreignUuid('attempt_id')->unique()->constrained()->cascadeOnDelete(); $t->foreignId('reviewer_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('status')->default('awaiting_review')->index(); $t->string('rubric_version')->default('ielts-criteria-2026-v1'); $t->json('criteria')->nullable(); $t->text('feedback')->nullable(); $t->decimal('band',3,1)->nullable(); $t->unsignedInteger('revision')->default(0); $t->timestamp('published_at')->nullable(); $t->timestamps(); });
  Schema::create('bookmarks', function(Blueprint $t){ $t->id(); $t->foreignId('user_id')->constrained()->cascadeOnDelete(); $t->foreignUuid('attempt_id')->constrained()->cascadeOnDelete(); $t->string('question_id'); $t->text('note')->nullable(); $t->timestamps(); $t->unique(['user_id','attempt_id','question_id']); });
  Schema::create('plans', function(Blueprint $t){ $t->id(); $t->string('name'); $t->text('description'); $t->boolean('active')->default(true); $t->timestamps(); });
  Schema::create('entitlements', function(Blueprint $t){ $t->id(); $t->foreignId('user_id')->constrained()->cascadeOnDelete(); $t->foreignId('plan_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('exam_id')->nullable()->constrained()->restrictOnDelete(); $t->string('source')->default('manual'); $t->timestamp('expires_at')->nullable(); $t->timestamp('revoked_at')->nullable(); $t->foreignId('granted_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); });
  Schema::create('payments', function(Blueprint $t){ $t->id(); $t->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $t->string('provider'); $t->string('event_id')->unique(); $t->string('status'); $t->integer('amount_minor'); $t->string('currency',3); $t->json('metadata')->nullable(); $t->timestamps(); });
  Schema::create('contacts', function(Blueprint $t){ $t->id(); $t->string('name'); $t->string('email'); $t->text('message'); $t->string('delivery_status')->default('stored_not_sent'); $t->string('status')->default('new'); $t->timestamps(); });
  Schema::create('settings', function(Blueprint $t){ $t->id(); $t->string('key')->unique(); $t->text('value')->nullable(); $t->timestamps(); });
  Schema::create('audit_events', function(Blueprint $t){ $t->id(); $t->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('action')->index(); $t->string('subject_type'); $t->string('subject_id'); $t->json('changes')->nullable(); $t->timestamp('created_at'); });
  Schema::create('notifications', function(Blueprint $t){ $t->uuid('id')->primary(); $t->string('type'); $t->morphs('notifiable'); $t->text('data'); $t->timestamp('read_at')->nullable(); $t->timestamps(); });
  Schema::create('media_assets', function(Blueprint $t){ $t->id(); $t->string('name'); $t->string('path'); $t->string('disk')->default('local'); $t->string('kind'); $t->text('description'); $t->text('transcript')->nullable(); $t->string('license')->default('Original demonstration content'); $t->timestamps(); });
 }
 public function down(): void { foreach(['media_assets','notifications','audit_events','settings','contacts','payments','entitlements','plans','bookmarks','assessments','recordings','attempt_mutations','attempts','exam_versions','exams','collections'] as $table) Schema::dropIfExists($table); Schema::table('users',fn(Blueprint $t)=>$t->dropColumn(['role','suspended','profile','deletion_requested_at'])); }
};
