import { useState,type FormEvent } from 'react';
import { Link,useNavigate,useParams,useSearchParams } from 'react-router-dom';
import { ArrowRight,BookOpen } from 'lucide-react';
import { api,clearDrafts,queryClient,csrf } from '../lib/api';
import { useSession } from '../lib/session';
import { ErrorBox,Success } from '../components/UI';
export function AuthPage({mode}:{mode:'login'|'register'|'forgot'|'reset'}){
 const [error,setError]=useState<unknown>();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const {refresh}=useSession();const navigate=useNavigate();const [params]=useSearchParams();const {token}=useParams();
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError(undefined);const d=Object.fromEntries(new FormData(e.currentTarget));try{await csrf();const result=await api<{message?:string}>(`/auth/${{login:'login',register:'register',forgot:'forgot-password',reset:'reset-password'}[mode]}`,'POST',{...d,token});if(mode==='login'||mode==='register'){clearDrafts();queryClient.clear();await refresh();const next=params.get('next');navigate(next?.startsWith('/')&&!next.startsWith('//')?next:mode==='register'?'/onboarding':'/dashboard');}else setMessage(result.message??'Saved.');}catch(e){setError(e);}finally{setBusy(false);}}
 return <div className="auth-layout"><div className="auth-story"><span className="eyebrow">YOUR NEXT CHAPTER</span><h1>Good things<br/>start with<br/><em>a little practice.</em></h1><p>A space to focus, learn from mistakes, and see how far you’ve come.</p><BookOpen size={110} strokeWidth={.8}/></div><div className="auth-card"><span className="eyebrow">IELTS PRACTICE HUB</span><h1>{{login:'Welcome back.',register:'Make a fresh start.',forgot:'Reset your password.',reset:'Choose a new password.'}[mode]}</h1><p className="muted">{mode==='register'?'Your learning journey starts here. Free to get started.':mode==='login'?'Pick up where you left off.':'We’ll help you get back to your learning.'}</p>{error?<ErrorBox error={error}/>:null}{message?<Success>{message} <Link to="/login">Return to login</Link></Success>:<form onSubmit={submit} className="form-stack">{mode==='register'&&<label>Your name<input name="name" autoComplete="name" required maxLength={100}/></label>}<label>Email address<input name="email" type="email" defaultValue={params.get('email')??''} autoComplete="email" required/></label>{mode!=='forgot'&&<label>Password<input name="password" type="password" minLength={mode==='login'?1:10} autoComplete={mode==='login'?'current-password':'new-password'} required/>{mode!=='login'&&<small>Use at least 10 characters.</small>}</label>}{['register','reset'].includes(mode)&&<label>Confirm password<input name="password_confirmation" type="password" autoComplete="new-password" required minLength={10}/></label>}{mode==='login'&&<Link className="text-button" to="/forgot-password">Forgot your password?</Link>}<button disabled={busy} className="button primary">{busy?'Please wait…':{login:'Log in',register:'Create your account',forgot:'Request reset link',reset:'Save new password'}[mode]}<ArrowRight size={17}/></button></form>}<p className="auth-switch">{mode==='login'?<>New here? <Link to="/register">Start learning for free</Link></>:<>Already have an account? <Link to="/login">Log in</Link></>}</p><p className="text-xs muted">By creating an account, you agree to the <Link to="/terms">draft terms</Link> and <Link to="/privacy">privacy notice</Link>.</p></div></div>;
}
