import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { api,human,isDone,queryClient } from '../lib/api';
import type { Progress as ProgressData,ReviewItem } from '../../../shared/api';
import { PageTitle,Loading,ErrorBox,Empty,skills,SkillIcon,Badge } from '../components/UI';
import { ArrowRight,Bookmark,Trash2,Check } from 'lucide-react';
import { useState } from 'react';
export function Progress(){const q=useQuery({queryKey:['progress'],queryFn:()=>api<ProgressData>('/progress')});if(q.isPending)return <Loading/>;if(q.error)return <ErrorBox error={q.error}/>;const d=q.data!;return <><PageTitle eyebrow="LOOK HOW FAR YOU’VE COME" title="Every session tells a story." description="See what is improving and find the questions that deserve another look."/><div className="skill-grid">{skills.map(s=><div className="panel padded" key={s}><span className={`icon-tile ${s}`}><SkillIcon skill={s}/></span><h3>{human(s)}</h3><p>{d.skills[s].completed} completed sessions</p>{d.skills[s].trend.length?<div className="trend-bars" aria-label={`${human(s)} accuracy trend`}>{d.skills[s].trend.slice(-10).map((p,i)=><div key={i} title={`${p.date}: ${p.accuracy!==null?p.accuracy+'% accuracy':p.band!==null?'Practice band '+p.band:'Awaiting review'}`}><span style={{height:`${p.accuracy??(p.band??0)/9*100}%`}}/><small>{p.accuracy!==null?p.accuracy+'%':p.band??'—'}</small></div>)}</div>:<p className="muted text-sm">Your first result will start this trend.</p>}</div>)}</div><div className="two-grid mt-6"><div className="panel padded"><h2>Question-type accuracy</h2>{Object.keys(d.question_types).length?Object.entries(d.question_types).map(([type,v])=><div className="accuracy-row" key={type}><div className="row between"><span>{human(type)}</span><strong>{v.correct}/{v.total}</strong></div><div className="progress-track"><span style={{width:`${100*v.correct/v.total}%`}}/></div></div>):<p className="muted">Complete Reading or Listening to see which question types need attention.</p>}</div><div className="panel padded"><h2>Your study activity</h2>{Object.entries(d.activity).slice(-14).map(([date,n])=><div className="row between activity-row" key={date}><span>{new Date(date+'T12:00:00').toLocaleDateString()}</span><Badge tone="green">{n} {n===1?'session':'sessions'} started</Badge></div>)}{!Object.keys(d.activity).length&&<p className="muted">No study activity yet. A short session is a great place to start.</p>}</div></div><div className="section-heading"><h2>Attempt history</h2></div><History/></>;}
function History(){const q=useQuery({queryKey:['attempt-history'],queryFn:()=>api<{data:import('../../../shared/api').Attempt[]}>('/attempts')});return <div className="panel attempt-list">{q.data?.data.map((a,i)=><Link className="attempt-row" key={a.id} to={`/${isDone(a.status)?'results':'attempts'}/${a.id}`}><span className="number-chip">{i+1}</span><div><strong>{a.exam?.title}</strong><small>{new Date(a.started_at).toLocaleString()} · {human(a.mode)}</small></div><Badge>{human(a.status)}</Badge><ArrowRight size={17}/></Link>)}{q.data?.data.length===0&&<Empty title="A clean slate.">Your attempts will appear here, including retakes.</Empty>}</div>;}
export function StudyPlan(){const q=useQuery({queryKey:['progress'],queryFn:()=>api<ProgressData>('/progress')});return <><PageTitle eyebrow="A RHYTHM YOU CAN KEEP" title="Make a little room for learning." description="A simple, rule-based plan shaped around your available time."/><div className="panel padded study-plan"><Badge tone="indigo">{q.data?.study_plan.daily_minutes??30} minutes a day</Badge><h2>One manageable session.</h2>{q.data?.study_plan.steps.map((s,i)=><div className="plan-step" key={s}><span className="step-number">0{i+1}</span><div><h3>{['Practise','Reflect','Focus'][i]}</h3><p>{s}</p></div></div>)}<p className="notice">{q.data?.recommendation.reason}</p><div className="row wrap"><Link className="button primary" to="/library">Find your practice <ArrowRight size={17}/></Link><Link className="button secondary" to="/settings">Adjust your daily goal</Link></div></div></>;}
export function Mistakes(){const q=useQuery({queryKey:['bookmarks'],queryFn:()=>api<{id:number;attempt_id:string;note:string;test:string;item:ReviewItem}[]>('/bookmarks')});const [error,setError]=useState<unknown>();return <><PageTitle eyebrow="TURN MISTAKES INTO MOMENTUM" title="Your personal learning notes." description="Save useful questions from your results and revisit what you learned."/>{error?<ErrorBox error={error}/>:null}{q.isPending?<Loading/>:q.error?<ErrorBox error={q.error}/>:!q.data?.length?<Empty title="A space for your discoveries.">Use “Save to notebook” on a result to keep a question and its explanation.</Empty>:<div className="notebook-list">{q.data.map(b=><article className="panel padded" key={b.id}><div className="row between"><Badge tone="indigo"><Bookmark size={13}/>{b.test}</Badge><button className="icon-button" aria-label="Remove saved mistake" onClick={async()=>{try{await api(`/bookmarks/${b.id}`,'DELETE');queryClient.invalidateQueries({queryKey:['bookmarks']});}catch(e){setError(e);}}}><Trash2 size={17}/></button></div><h3>{b.item?.prompt}</h3><p className="muted">Your answer: {String(b.item?.your_answer||'No answer')}</p><p className="correct-text"><Check size={16}/>Accepted: {b.item?.accepted.join(' / ')}</p><p>{b.item?.explanation}</p>{b.note&&<blockquote>{b.note}</blockquote>}<Link className="text-button" to={`/results/${b.attempt_id}`}>Return to full review <ArrowRight size={16}/></Link></article>)}</div>}</>;}
